### ISSUE TITLE
Nightly clio-integration test is flaky.

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#659]
[https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/](https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/)

Fails in different ways on different days.

Most look like timeouts waiting for the docker container to start.

Some look like mysterious build failures.

And occasionally it succeeds.

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-339)

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Success looks like this.

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/896/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/896 )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Failed waiting for test docker container.

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/897/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/897 )

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/898/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/898 )

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/899/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/899 )

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/900/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/900 )

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/901/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/901 )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/902/console ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/902/console )

00:51:19 00:51:19.798 [pool-1-thread-1] INFO  🐳 [docker-compose] - Docker Compose has finished running
00:51:19 00:51:19.802 [pool-1-thread-1] INFO  🐳 [docker.io/alpine/socat:latest] - Creating container for image: docker.io/alpine/socat:latest
00:51:21 00:51:21.368 [pool-1-thread-1] INFO  🐳 [docker.io/alpine/socat:latest] - Starting container with ID: 454285d0b595b11ad1d80c33fb9d605fe53f0baa20aee84811547332d4becd5c
00:52:44 Exception in thread "Thread-16" java.io.EOFException
00:52:44 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2903)
00:52:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1502)
00:52:44 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
00:52:44 	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:818)
00:52:44 	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:807)
00:52:44 	at java.lang.Thread.run(Thread.java:745)

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Mysterious build failure.

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/903 ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/903/console )/

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/904 ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/904/console )/

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/905/ ( https://gotc-jenkins.dsp-techops.broadinstitute.org/view/greenteam-nightly/job/clio-integration/905/console )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

One of the runs failed with "process_cluster_event_timeout_exception"

indicating a timeout talking to Elasticsearch. Jenkins has since purged it though.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster ( https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Logged in but didn’t notice anything.

gcloud compute --project broad-gotc-dev ssh gotc-build-dev101

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Local build usually succeeds, but occasionally fails with a container start-up timeout.

tbl@wm97a-c2b ~/Broad/clio # java -jar /usr/local/Cellar/sbt/1.2.8/libexec/bin/sbt-launch.jar "it:testOnly *DevEnv* *LoadIntegrationSpec *RecoveryIntegrationSpec *AuthIntegrationSpec"
[info] Loading global plugins from /Users/tbl/.sbt/0.13/plugins
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Loading project definition from /Users/tbl/Broad/clio/project/project
...
17:39:50.148 [Thread-25] ERROR 🐳 [docker-compose] - 
17:39:50.382 [Thread-25] ERROR 🐳 [docker-compose] - Removing dxdfesqrjfxo_elasticsearch2_1 ... doneRemoving dxdfesqrjfxo_clio-server_1    ... doneRemoving dxdfesqrjfxo_elasticsearch1_1 ... doneRemoving network dxdfesqrjfxo_clio-networkRemoving volume dxdfesqrjfxo_esdata1
17:39:50.455 [Thread-25] ERROR 🐳 [docker-compose] - Removing volume dxdfesqrjfxo_esdata2
17:39:50.567 [pool-1-thread-1] INFO  🐳 [docker-compose] - Docker Compose has finished running
[info] Run completed in 1 hour, 39 minutes, 52 seconds.
[info] Total number of tests run: 132
[info] Suites: completed 7, aborted 0
[info] Tests: succeeded 132, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 5996 s, completed Jul 15, 2019 5:40:17 PM
tbl@wm97a-c2b ~/Broad/clio #
