### ISSUE TITLE
Memory problems with exome cram data delivery

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#710]
We're seeing repeated failures involving out of memory errors for some exome deliveries. Specifically, PO-17775.

Logs are written on-prem in /seq/tng/picard/fireCloudDelivery/PO-17775.  "cromwell.11.log" contains info about the latest run, including:

```
[ERROR] [06/05/2019 20:59:23.121] [cromwell-system-akka.dispatchers.service-dispatcher-153] [akka://cromwell-system/user/SingleWorkflowRunnerActor/ServiceRegistryActor/MetadataService/WriteMetadataActor] WriteMetadataActor Failed to properly process data
java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15(JdbcActionComponent.scala:530)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15$adapted(JdbcActionComponent.scala:528)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$14(JdbcActionComponent.scala:528)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:386)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:381)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:448)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:501)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:526)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
	at slick.dbio.SynchronousDatabaseAction$$anon$7.run(DBIOAction.scala:486)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SessionData.allocateLobForResult(Unknown Source)
	at org.hsqldb.Session.allocateResultLob(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source)
	... 33 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.persist.LobStoreMem.setBlockBytes(Unknown Source)
	at org.hsqldb.persist.LobManager.setBytesISNormal(Unknown Source)
	at org.hsqldb.persist.LobManager.setBytesIS(Unknown Source)
	at org.hsqldb.persist.LobManager.setCharsForNewClob(Unknown Source)
	at org.hsqldb.SessionData.allocateLobForResult(Unknown Source)
	at org.hsqldb.Session.allocateResultLob(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15(JdbcActionComponent.scala:530)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$15$adapted(JdbcActionComponent.scala:528)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$Lambda$2532/1424730004.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$14(JdbcActionComponent.scala:528)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$Lambda$2529/1027218512.apply(Unknown Source)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:386)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:381)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:448)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:501)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:526)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
	at slick.dbio.DBIOAction$$anon$4$$Lambda$2525/1210694056.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
```

and

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "cromwell-system-shutdown-hook-1" java.lang.InternalError: linkToTargetMethod=Lambda(a0:L,a1:L,a2:I,a3:L,a4:L,a5:L,a6:L)=>{
    t7:L=MethodHandle.invokeBasic(a6:L,a0:L,a1:L,a2:I,a3:L,a4:L,a5:L);t7:L}
	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
	at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
	at java.lang.invoke.Invokers.callSiteForm(Invokers.java:381)

	at java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:347)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:314)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at akka.actor.CoordinatedShutdown.liftedTree1$1(CoordinatedShutdown.scala:465)
	at akka.actor.CoordinatedShutdown.loop$1(CoordinatedShutdown.scala:463)
	at akka.actor.CoordinatedShutdown.run(CoordinatedShutdown.scala:495)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "cromwell-system-shutdown-hook-1"
java.lang.OutOfMemoryError: GC overhead limit exceeded
Uncaught error from thread [cromwell-system-akka.dispatchers.backend-dispatcher-232cromwell-system-akka.actor.default-dispatcher-274]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cromwell-system]
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-295)

**Comment by kbergin** [comment]
➤ Gordon Wade commented:

Seeing this affecting some more deliveries. Going to link them here to help keep track and keep visibility on this issue.

**Comment by kbergin** [comment]
➤ Nikelle Petrillo commented:

Linking another workflow I’m seeing failing with this OOM error 🙁  

https://broadinstitute.atlassian.net/browse/PO-18057 ( https://broadinstitute.atlassian.net/browse/PO-18057|smart-link )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

[~gwade] [~npetrill] I don’t know how that Cromwell is configured, but you’re gonna have to give it more heap to run in.

**Comment by kbergin** [comment]
➤ Gordon Wade commented:

I believe dependencies for this live at /seq/cloud/prod/workflows/dependencies/workflow_dependencies.zip It sounds like we need to change this and run with a custom zip? Do we know which step needs increasing?

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

I think we need to increase the heap space devoted to the Cromwell JVM

because a Cromwell Akka thread threw the exception.

How is this Cromwell configured?

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

BTW: It looks like Cromwell is spinning in the garbage collector while trying to build a string.

I wonder how big that string can get … whatever it is.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Yikes. It appears to fail trying to write the “background script” which tends to be tiny.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

For example: This is the last one written successfully.

/seq/tng/picard/fireCloudDelivery/PO-17775/cromwell-executions/ExomeCramDataDelivery/983f1af1-856a-4356-9533-f1fab5e2ca47/call-CramDataDelivery/CramDataDelivery/fa2fd26e-399f-4bca-9f59-530678cb0494/call-MoveSamples/shard-264/execution/script.background

**Comment by kbergin** [comment]
➤ Gordon Wade commented:

[~tbl], [~jkaneria], we recently moved v2 delivery to a cloud cromwell instance. Running on this instance has fixed this problem in at least two of our cases. If it fixes the remaining cases, we should be able to close this ticket.
