### ISSUE TITLE
Zigs/prod - Problem composing aggregation for RP-1739.ShortRangePCR.YL237072S02

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#712]
**Janki’s Update: The fix to this issue would be to remove the create ticket functionality for this error message. An email will suffice in this case.** 

A problem was encountered generating a message for this aggregation.  The requests associated with it have been purged from the pending aggregation queue.

AggregationParameters(RP-1739.ShortRangePCR.YL237072S02,RP-1739,Some(ShortRangePCR),Set(LIBRARY, SAMPLE),true,Some(P-MCV-0011),BySampleAlias)

Read groups requesting this submission:
flowcell=CFRJ7; lane=1; library=SM-IMS5G_Illumina_P5-Hohez_P7-Fojol; library_type=TargetedAmplicon; analysis_type=AssemblyWithoutReference; ref=Plasmodium_falciparum_3D7_hybrid_plasmids_CSP_SERA2; datatype=ShortRangePCR

Causal exception:

Causal exception: Project /seq/picard_aggregation/RP-1739 does not define datatype.

```java
org.broadinstitute.zamboni.client.zigs.AggregationSubmitter$MessageBuilderException: Project /seq/picard_aggregation/RP-1739 does not define datatype.
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitter.submitAggregation(AggregationSubmitter.scala:266)
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitter$$anonfun$processAndSubmitPendingAggregations$4.apply(AggregationSubmitter.scala:116)
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitter$$anonfun$processAndSubmitPendingAggregations$4.apply(AggregationSubmitter.scala:113)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitter.processAndSubmitPendingAggregations(AggregationSubmitter.scala:113)
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitterSweeper.sweep(AggregationSubmitterSweeper.scala:37)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter$$anonfun$act$2$$anonfun$apply$mcV$sp$2.applyOrElse(PeriodicSweeper.scala:172)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at scala.actors.InternalActor$class.receive(InternalActor.scala:123)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter.receive(PeriodicSweeper.scala:153)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter$$anonfun$act$2.apply$mcV$sp(PeriodicSweeper.scala:159)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter$$anonfun$act$2.apply(PeriodicSweeper.scala:159)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter$$anonfun$act$2.apply(PeriodicSweeper.scala:159)
at scala.actors.Reactor$class.seq(Reactor.scala:286)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter.seq(PeriodicSweeper.scala:153)
at scala.actors.Reactor$$anon$3.andThen(Reactor.scala:264)
at scala.actors.Combinators$class.loop(Combinators.scala:28)
at org.broadinstitute.zamboni.client.util.sweep.PeriodicSweeper$Submitter.loop(PeriodicSweeper.scala:153)
at scala.actors.Combinators$$anonfun$loop$1.apply(Combinators.scala:28)
at scala.actors.Combinators$$anonfun$loop$1.apply(Combinators.scala:28)
at scala.actors.Reactor$$anonfun$seq$1$$anonfun$apply$1.applyOrElse(Reactor.scala:283)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at scala.actors.ReactorTask.run(ReactorTask.scala:31)
at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: picard.PicardException: Project /seq/picard_aggregation/RP-1739 does not define datatype.
at org.broadinstitute.picard.priv.core.util.PicardAggregationDirectories$Project.getDataType(PicardAggregationDirectories.java:175)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder$$anonfun$2.apply(ProductionAggregationMessageBuilder.scala:57)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder$$anonfun$2.apply(ProductionAggregationMessageBuilder.scala:57)
at scala.Option.flatMap(Option.scala:171)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder$.getExtantVersionDirectoriesForSample(ProductionAggregationMessageBuilder.scala:57)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder$$anonfun$generateWorkflowMessage$2.apply(ProductionAggregationMessageBuilder.scala:308)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder$$anonfun$generateWorkflowMessage$2.apply(ProductionAggregationMessageBuilder.scala:296)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
at org.broadinstitute.zamboni.client.zigs.ProductionAggregationMessageBuilder.generateWorkflowMessage(ProductionAggregationMessageBuilder.scala:296)
at org.broadinstitute.zamboni.client.zigs.AggregationSubmitter.submitAggregation(AggregationSubmitter.scala:267)
... 35 more
```

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-291)

**Comment by kbergin** [comment]
➤ Sam Novod commented:

Data type is defined in read_group_index

{quote}~select distinct i.flowcell_barcode, i.lane, i.library_name, i.AGGREGATION_PROJECT, i.SAMPLE_ALIAS, i.DATA_TYPE from READ_GROUP_INDEX i where i.sample_alias = 'YL237072S02';~{quote}

and the RP directory looks the same as other RPs. Not sure what is causing this failure.

$ ls  /seq/picard_aggregation/RP-173*
/seq/picard_aggregation/RP-1735:
WGS/  directory.properties

/seq/picard_aggregation/RP-1737:
Exome/	WGS/  directory.properties

/seq/picard_aggregation/RP-1739:
ShortRangePCR/	directory.properties

$ cat  /seq/picard_aggregation/RP-173*/directory.properties
structure=project/datatype/sample/version
structure=project/datatype/sample/version
structure=project/datatype/sample/version

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

This appears to be the source of the exception.

https://github.com/broadinstitute/picard-private/blob/develop/core/src/main/java/org/broadinstitute/picard/priv/core/util/PicardAggregationDirectories.java#L168-L180 ( https://github.com/broadinstitute/picard-private/blob/develop/core/src/main/java/org/broadinstitute/picard/priv/core/util/PicardAggregationDirectories.java#L168-L180|smart-link )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

… and Jira is a POS.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Yeah [~samn], but there are a LOT more SAMPLEs under the ShortRangePCR DATATYPE.

tbl@picard-vm /seq/picard_aggregation # ls -l RP-1737/* | wc
     27     195    1245
tbl@picard-vm /seq/picard_aggregation # ls -l RP-1739/* | wc
   9615   86511  531370
tbl@picard-vm /seq/picard_aggregation #

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

PicardAggregationDirectories is an amazing piece of work.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Zamboni calls that amazing piece of work from here.

https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/ProductionAggregationMessageBuilder.scala#L67-L84 ( https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/ProductionAggregationMessageBuilder.scala#L67-L84|smart-link ) 

So that structure is not read from the filesystem.

Instead it is composed by Zamboni.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

And WeverTF that’s doing, it is evidently resulting in this thing.

https://github.com/broadinstitute/zamboni/blob/develop/Workflows/src/scala/org/broadinstitute/picard/steprunners/WriteAggregationDirectoryStructure.scala#L49-L54 ( https://github.com/broadinstitute/zamboni/blob/develop/Workflows/src/scala/org/broadinstitute/picard/steprunners/WriteAggregationDirectoryStructure.scala#L49-L54|smart-link )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Maybe https://github.com/broadinstitute/zamboni/pull/1841 ( https://github.com/broadinstitute/zamboni/pull/1841|smart-link )

**Comment by kbergin** [comment]
➤ Jessica Way commented:

The error is being generated here ( https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/AggregationSubmitter.scala#L125 )

**Comment by kbergin** [comment]
➤ Jessica Way commented:

None of the Custom_Selection workflows have directory.properties files. I suspect this may be an error related to the periods in the name of the aggregation projects for these workflows.  Hopefully this issue will be addressed by the fix from this ticket ( https://broadinstitute.atlassian.net/browse/GL-160 ), which should be released today. The failures in the RNA, Exome, and ShortRangePCR workflows are not explained by the same issue

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Interesting. The workflows [~samn] initially reported do have directory.property files.

**Comment by kbergin** [comment]
➤ Jessica Way commented:

yeah, the RNA, Exome, and ShortRangePCR workflows all have the directory.property files

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Evidently, the AggregationParameters have a null or None for dataType.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Hmm. This is probably a red herring, but I see …

WARNING 2018-11-02 16:35:11     ProductionAggregationSpecificationGenerator$    aggregationDataType: ShortRangePCR is not supported… in some old notes. 

https://github.com/broadinstitute/tbl/blob/master/bugs/DSDEGP-2844.org#background ( https://github.com/broadinstitute/tbl/blob/master/bugs/DSDEGP-2844.org#background|smart-link )

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Is ShortRangePCR a dataType or a libraryType? Both?

https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/AggregationSpecificationGenerator.scala#L203-L213 ( https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/AggregationSpecificationGenerator.scala#L203-L213|smart-link )

**Comment by kbergin** [comment]
➤ Jessica Way commented:

If the information is coming from the READ_GROUP_INDEX table, then I think 'ShortRangePCR' is the data type. The library type for that particular failed workflow is 'TargetedAmplicon'

(select * from READ_GROUP_INDEX i where i.sample_alias = 'YL237072S02')

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

Some of these are definitely symptoms of the “dot in aggregation project” bug.

https://broadinstitute.atlassian.net/browse/GL-160 ( https://broadinstitute.atlassian.net/browse/GL-160|smart-link )

**Comment by kbergin** [comment]
➤ Sam Novod commented:

Added read group index id in PENDING_AGGREGATION_READ_GROUP

**Comment by kbergin** [comment]
➤ Janki Kaneria commented:

Looks like linked PO tickets have been closed. Is there obvious engineering work that needs to be don to prevent this in the future(aka something I can turn into a ticket and backlog)?

**Comment by kbergin** [comment]
➤ Sam Novod commented:

Hi [~jkaneria] ,

I think the engineering problems has been fixed and this ticket can be closed.

Thanks,

Sam

**Comment by kbergin** [comment]
➤ Sam Novod commented:

I might of spoken too soon.. We just got the below failures.

PO-18839
PO-18838
PO-18840
PO-18843

**Comment by kbergin** [comment]
➤ Sam Novod commented:

Hi [~jkaneria], all of the above ticket also had all their read groups blacklisted, so we should of just received an email saying it is skipping those aggregations because all read groups are blacklisted and not ticket.

An analysis of RP-1994.WGS.microbial_water_9/microbial_water_9 was requested, but it is being skipped because all its read groups are blacklisted.

**Comment by kbergin** [comment]
➤ Tom Lyons commented:

So we can still close this?

**Comment by kbergin** [comment]
➤ Janki Kaneria commented:

I'm moving this to a backlog of issues that need to be fixed.

**Comment by kbergin** [comment]
➤ Charlotte Tolonen commented:

To be clear, I think we need/want a ticket when the data type is the problem, but don’t need one when all read groups are blacklisted. The difference is that we go back to GP to fix the datatype but we don’t do anything when all read groups are blacklisted and don’t need aggregations.

**Comment by kbergin** [comment]
➤ Charles Yan commented:

I believe some time in the past there was a request to create Jira tickets for one kind of problem. The implementation ended up coupling Zigs' email and Jira notifiers together, unintentionally causing Jira tickets to be spawned for all errors that went through the notifier. Probably a good place to look to start working on decoupling the notifiers: https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/Zigs.scala#L97-L104 ( https://github.com/broadinstitute/zamboni/blob/develop/Client/src/scala/org/broadinstitute/zamboni/client/zigs/Zigs.scala#L97-L104|smart-link )
