### ISSUE TITLE
Check that the Optimus V3 is comparable to the outputs obtained by Cellranger

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#803]
Generally, we have validated our Optimus pipeline by comparing it to the community standard, Cellranger, which is the software made by 10X, who also makes this library construction. Our aim is to make sure that the pipeline reasonably outputs similar results so that we can move on to a larger validation.

AC:

* Make sure that the data look comparable with the output provided by 10X

If the results are not correct, debug why they are not the same and spin out new tickets to fix if large effort.

┆Issue is synchronized with this [Jira Dev Task](https://broadinstitute.atlassian.net/browse/GL-629)

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

Following up from the previous ticket this is the run that succeeded, but the output matrix appears to be missing many reads:

https://job-manager.caas-prod.broadinstitute.org/jobs/20154f5b-b749-49bb-8493-8c7f5cf40c68 ( https://job-manager.caas-prod.broadinstitute.org/jobs/20154f5b-b749-49bb-8493-8c7f5cf40c68 )

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

As outlined in the spike ticket the Optimus output had a much lower number of reads recorded. I investigated the cause of this and the reason is that many reads are not correctly tagged with the corrected cellular barcode tag. 

This can be demonstrated using the following steps on the Optimus bam and the 10X bam:

$ samtools view -@ 6 pbmc_10k_v3_possorted_genome_bam.bam 21 | grep -F 'CB:Z:' | wc -l
7948130
$ samtools view -@ 6 pbmc_10k_v3_possorted_genome_bam.bam 21 | wc -l
9290404
$ samtools view -@ 6 merged.bam chr21 | grep -F 'CB:Z:' | wc -l
174318
$ samtools view -@ 6 merged.bam chr21 | wc -l
9281221As can be seem from the above ~80% of the reads in the bam provided by 10X have a CB barcode but ~1% of the ones from Optimus do. This point to a bug in the new code.

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

New run with 3M barcodes: https://job-manager.caas-prod.broadinstitute.org/jobs/90b253ae-29f6-42a0-98e3-29e394fd2629 ( https://job-manager.caas-prod.broadinstitute.org/jobs/90b253ae-29f6-42a0-98e3-29e394fd2629 )

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

After fail in AttachBarcodes with apparently truncated error, re-running with more disk and RAM. Next step is to add monitoring and/or run the step manually.

https://job-manager.caas-prod.broadinstitute.org/jobs/038ed0e0-f6c8-4582-a6d2-d115cb4d96cd ( https://job-manager.caas-prod.broadinstitute.org/jobs/038ed0e0-f6c8-4582-a6d2-d115cb4d96cd )

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

I have confirmed that the problem is memory requirements, even after increasing to 16GB, this step still fails: 

Traceback (most recent call last):
  File "/usr/local/bin/AttachBarcodes", line 11, in <module>
    load_entry_point('sctools==0.3.4', 'console_scripts', 'AttachBarcodes')()
  File "/usr/local/lib/python3.6/site-packages/sctools/platform.py", line 1083, in attach_barcodes
    tag_generators = cls._make_tag_generators(args.r1, args.i1, args.whitelist)
  File "/usr/local/lib/python3.6/site-packages/sctools/platform.py", line 949, in _make_tag_generators
    fastq.BarcodeGeneratorWithCorrectedCellBarcodes(**barcode_args)
  File "/usr/local/lib/python3.6/site-packages/sctools/fastq.py", line 361, in __init__
    whitelist
  File "/usr/local/lib/python3.6/site-packages/sctools/barcode.py", line 354, in single_hamming_errors_from_whitelist
    cls._prepare_single_base_error_hash_table((line[:-1] for line in f))
  File "/usr/local/lib/python3.6/site-packages/sctools/barcode.py", line 334, in _prepare_single_base_error_hash_table
    error_map[barcode[:i] + e + barcode[i + 1 :]] = barcode
MemoryErrorI will increase memory further and try again. This may require further work to reduce the memory footprint of this task.

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

Latest run with more memory that has passed AttachBarcodes is here:

https://job-manager.caas-prod.broadinstitute.org/jobs/9523505b-decc-434a-b748-8a8ef4e90b58 ( https://job-manager.caas-prod.broadinstitute.org/jobs/9523505b-decc-434a-b748-8a8ef4e90b58 )

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

Resulting document for analysis is here: https://docs.google.com/document/d/1-hwfXkqtL8MblgDWFzk-HsVRYiy4PS8ZhJqAGlHBWYE/edit# ( https://docs.google.com/document/d/1-hwfXkqtL8MblgDWFzk-HsVRYiy4PS8ZhJqAGlHBWYE/edit#|smart-link )

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

I asked for CB review from  [~accountid:5ba003187ec0fb2e420b1942] [~accountid:557058:f258569c-acb2-4486-a9e8-96dc2d9ec8d1] [~accountid:557058:e7bdb236-62ec-4185-bcf1-f4399033e260]

**Comment by kbergin** [comment]
➤ Nick Barkas commented:

Comments on document addressed and moving to QA
